version: "3.9"

services:
  db:
    image: postgres:16.4-alpine
    ports:
      - ${LOCAL_DB_PORT:-15432}:5432
    volumes:
      - ./${POSTGRES_DATA:-postgres-data}:/var/lib/postgresql/data:cached
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT